#!/usr/bin/env python3
"""Regenerate tests/mock_key.inc — a throwaway RSA keypair for the TLS tests.

This is NOT a credential. It is a 1024-bit key generated once for the sole
purpose of letting the test suite play a TLS server: the mock needs the private
exponent so it can decrypt the ClientKeyExchange, agree on the master secret,
and produce a Finished the client will accept. Without it, test_client can only
watch the client's flight and never confirm that a handshake completes — which
would leave the transcript ordering in client.hpp unverified, and that ordering
is exactly the sort of thing that is wrong until something checks it.

The corresponding production tree deliberately contains NO big-exponent modexp,
so that an unhardened private-key operation is never casually reachable. The
test builds one locally out of BigInt's public mulmod.

Regenerate the inputs with:

    openssl req -x509 -newkey rsa:1024 -keyout mock_key.pem -out mock_cert.pem \\
        -days 36500 -nodes -subj "/CN=mock-tls-server/O=ilo2-console tests"
    openssl x509 -in mock_cert.pem -outform DER -out mock_cert.der
    python tests/gen_mock_key.py mock_cert.der mock_key.pem > tests/mock_key.inc
"""
import re
import subprocess
import sys


def wrap(hexstr, per_line=32):
    for i in range(0, len(hexstr), per_line * 2):
        yield hexstr[i:i + per_line * 2]


def emit(name, value_hex):
    print(f"[[maybe_unused]] static const char* {name} =")
    lines = list(wrap(value_hex))
    for i, line in enumerate(lines):
        tail = ";" if i == len(lines) - 1 else ""
        print(f'    "{line}"{tail}')


def field(text, label):
    """Pull a big-endian hex integer out of `openssl rsa -text` output."""
    m = re.search(label + r":\s*\n((?:\s+[0-9a-f:]+\n)+)", text)
    if not m:
        m = re.search(label + r":\s*([0-9]+)", text)
        if m:
            return f"{int(m.group(1)):x}".rjust(2, "0")
        raise SystemExit("cannot find " + label)
    raw = m.group(1).replace(":", "").replace(" ", "").replace("\n", "")
    return raw.lstrip("0") or "0"


def main():
    der_path, key_path = sys.argv[1], sys.argv[2]
    der = open(der_path, "rb").read()
    text = subprocess.run(["openssl", "rsa", "-in", key_path, "-noout", "-text"],
                          capture_output=True, text=True, check=True).stdout

    modulus = field(text, "modulus")
    priv = field(text, "privateExponent")

    print("// Generated by tests/gen_mock_key.py -- do not edit by hand.")
    print("//")
    print("// A THROWAWAY RSA-1024 keypair, generated solely so the test suite can")
    print("// play a TLS server. It is not a credential and protects nothing; the")
    print("// private exponent is published here on purpose. Never use it for")
    print("// anything but these tests.")
    print()
    print(f"// certificate: {len(der)} bytes DER")
    emit("MOCK_CERT_DER_HEX", der.hex())
    print()
    emit("MOCK_MODULUS_HEX", modulus)
    print()
    emit("MOCK_PRIVATE_EXPONENT_HEX", priv)


if __name__ == "__main__":
    main()
