#!/usr/bin/env python3
"""Regenerate tests/prf_vectors.inc.

Expected values come from OpenSSL's TLS1-PRF KDF with the MD5-SHA1 digest,
which IS the TLS 1.0/1.1 PRF:

    openssl kdf -keylen N -kdfopt digest:MD5-SHA1 \\
                -kdfopt hexsecret:... -kdfopt hexseed:... TLS1-PRF

Using OpenSSL rather than a Python reimplementation is deliberate. RFC 2246
publishes no PRF test vectors, so a hand-written Python version would only
confirm that two implementations share whatever misreading of section 5 I
happened to have. OpenSSL is an independent, long-audited implementation of the
same spec, which is a real oracle.

OpenSSL's "seed" parameter is the label concatenated with the seed, exactly as
the RFC defines PRF(secret, label, seed).

Requires an `openssl` on PATH with the kdf command (OpenSSL 3.x).

    python tests/gen_prf_vectors.py > tests/prf_vectors.inc
"""
import hashlib
import subprocess
import sys


def openssl_prf(secret: bytes, label: bytes, seed: bytes, outlen: int) -> bytes:
    out = subprocess.run(
        ["openssl", "kdf", "-keylen", str(outlen),
         "-kdfopt", "digest:MD5-SHA1",
         "-kdfopt", "hexsecret:" + secret.hex(),
         "-kdfopt", "hexseed:" + (label + seed).hex(),
         "TLS1-PRF"],
        capture_output=True, text=True, check=True).stdout.strip()
    return bytes.fromhex(out.replace(":", ""))


def blob(tag: bytes, n: int) -> bytes:
    """Deterministic filler, so the generated file is reproducible."""
    out = b""
    h = hashlib.sha256(tag).digest()
    while len(out) < n:
        h = hashlib.sha256(h).digest()
        out += h
    return out[:n]


CASES = [
    # (description, secret_len, label, seed_len, out_len)
    ("even secret, one MD5 block",            16, b"test label", 16, 16),
    ("even secret, partial final chunk",      16, b"test label", 16, 37),
    ("output shorter than one digest",        16, b"test label", 16, 5),
    ("long output, many P_hash iterations",   16, b"test label", 16, 200),
    # Odd secret lengths are the interesting case: S1 and S2 must OVERLAP by one
    # byte. A floor-based split passes every even-length vector and fails these.
    ("odd secret (1 byte, halves identical)",  1, b"odd", 8, 32),
    ("odd secret (3 bytes)",                   3, b"odd", 8, 32),
    ("odd secret (47 bytes)",                 47, b"odd", 64, 48),
    ("odd secret (49 bytes)",                 49, b"odd", 64, 48),
    ("empty seed",                            32, b"label only", 0, 24),
    # The real TLS 1.0 derivations, at their true sizes.
    ("master secret",                         48, b"master secret", 64, 48),
    ("key expansion for RC4_128_MD5",         48, b"key expansion", 64, 64),
    ("client finished",                       48, b"client finished", 36, 12),
    ("server finished",                       48, b"server finished", 36, 12),
]


def main():
    print("// Generated by tests/gen_prf_vectors.py -- do not edit by hand.")
    print("// Expected values come from OpenSSL's TLS1-PRF KDF with the MD5-SHA1")
    print("// digest, which is the TLS 1.0/1.1 PRF. RFC 2246 publishes no PRF test")
    print("// vectors, so an independent implementation is the only real oracle.\n")
    print("struct PrfVec { const char* desc; const char* secret_hex; const char* label;")
    print("                const char* seed_hex; size_t outlen; const char* want; };")
    print("[[maybe_unused]] static const PrfVec PRF_VECTORS[] = {")

    for desc, slen, label, seedlen, outlen in CASES:
        secret = blob(b"secret:" + desc.encode(), slen)
        seed = blob(b"seed:" + desc.encode(), seedlen)
        want = openssl_prf(secret, label, seed, outlen)
        print(f'    {{ "{desc}",')
        print(f'      "{secret.hex()}",')
        print(f'      "{label.decode()}",')
        print(f'      "{seed.hex()}",')
        print(f'      {outlen}, "{want.hex()}" }},')
    print("};")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as e:
        sys.exit(f"openssl kdf failed: {e.stderr}")
