#!/usr/bin/env python3
"""Regenerate tests/hash_vectors.inc.

Inputs are the canonical FIPS 180 (SHA-1) and RFC 2202 (HMAC-MD5, HMAC-SHA1)
test cases; the expected outputs are computed here with Python's hashlib/hmac
rather than transcribed, so a typo in the reference values is not possible.

    python tests/gen_hash_vectors.py > tests/hash_vectors.inc
"""
import hashlib
import hmac

# --- FIPS 180 / common SHA-1 cases -----------------------------------------
SHA1_INPUTS = [
    b"",
    b"abc",
    b"message digest",
    b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
    b"The quick brown fox jumps over the lazy dog",
    b"The quick brown fox jumps over the lazy cog",   # one-letter change
    bytes(range(256)),                                 # all byte values
    b"a" * 64,                                         # exactly one block
    b"a" * 63,                                         # one byte short
    b"a" * 65,                                         # one byte over
    b"a" * 119,                                        # forces the 120-idx pad path
    b"a" * 120,
]

# --- RFC 2202 HMAC cases (shared by MD5 and SHA-1) --------------------------
HMAC_INPUTS = [
    (b"\x0b" * 16, b"Hi There"),
    (b"Jefe", b"what do ya want for nothing?"),
    (b"\xaa" * 16, b"\xdd" * 50),
    (bytes(range(1, 26)), b"\xcd" * 50),
    (b"\x0c" * 16, b"Test With Truncation"),
    (b"\xaa" * 80, b"Test Using Larger Than Block-Size Key - Hash Key First"),
    (b"\xaa" * 80,
     b"Test Using Larger Than Block-Size Key and Larger Than One Block-Size Data"),
    # RFC 2202's SHA-1 cases use 20-byte keys where MD5 uses 16.
    (b"\x0b" * 20, b"Hi There"),
    (b"\xaa" * 20, b"\xdd" * 50),
    (b"\x0c" * 20, b"Test With Truncation"),
    # Key exactly at, and one past, the 64-byte block boundary.
    (b"\xaa" * 64, b"key is exactly one block"),
    (b"\xaa" * 65, b"key is one byte over a block"),
    (b"", b"empty key"),
]


def main():
    print("// Generated by tests/gen_hash_vectors.py -- do not edit by hand.")
    print("// Inputs are the canonical FIPS 180 / RFC 2202 cases; expected values are")
    print("// computed by Python's hashlib/hmac rather than transcribed by hand.\n")

    print("struct HashVec { const char* data_hex; const char* want; };")
    print("[[maybe_unused]] static const HashVec SHA1_VECTORS[] = {")
    for d in SHA1_INPUTS:
        print(f'    {{ "{d.hex()}", "{hashlib.sha1(d).hexdigest()}" }},')
    print("};\n")

    # A million 'a' is too large to embed; the test builds it in a loop.
    million = hashlib.sha1(b"a" * 1000000).hexdigest()
    print(f'[[maybe_unused]] static const char* SHA1_MILLION_A = "{million}";\n')

    print("struct HmacVec { const char* key_hex; const char* data_hex;")
    print("                 const char* want_md5; const char* want_sha1; };")
    print("[[maybe_unused]] static const HmacVec HMAC_VECTORS[] = {")
    for k, d in HMAC_INPUTS:
        m = hmac.new(k, d, hashlib.md5).hexdigest()
        s = hmac.new(k, d, hashlib.sha1).hexdigest()
        print(f'    {{ "{k.hex()}", "{d.hex()}",\n      "{m}", "{s}" }},')
    print("};")


if __name__ == "__main__":
    main()
