#!/usr/bin/env python3
"""Regenerate tests/record_vectors.inc.

An independent Python model of TLS 1.0 record protection for an RC4 suite.
Unlike the PRF, there is no third-party oracle to lean on here -- OpenSSL will
not emit a single protected record under keys of my choosing -- so this is a
second implementation by the same author, which catches transcription slips but
cannot catch a shared misreading of RFC 2246 section 6.2. The final arbiter is
the live handshake: a wrong MAC layout draws an immediate bad_record_mac.

What it CAN pin down, and what the negative vectors below are for, is that each
field genuinely participates: a record whose MAC was computed over a different
sequence number, or a different version, must be rejected even though its
keystream position is correct. Those cases isolate one variable at a time, which
a round-trip test cannot do.

    python tests/gen_record_vectors.py > tests/record_vectors.inc
"""
import hashlib
import hmac

VERSION = 0x0301
CT_HANDSHAKE = 22
CT_APPLICATION_DATA = 23
CT_ALERT = 21


class RC4:
    """Standard RC4. One instance per direction, living for the whole
    connection -- the keystream must not restart per record."""

    def __init__(self, key):
        S = list(range(256))
        j = 0
        for i in range(256):
            j = (j + S[i] + key[i % len(key)]) & 0xFF
            S[i], S[j] = S[j], S[i]
        self.S, self.i, self.j = S, 0, 0

    def crypt(self, data):
        S, i, j = self.S, self.i, self.j
        out = bytearray()
        for b in data:
            i = (i + 1) & 0xFF
            j = (j + S[i]) & 0xFF
            S[i], S[j] = S[j], S[i]
            out.append(b ^ S[(S[i] + S[j]) & 0xFF])
        self.i, self.j = i, j
        return bytes(out)


def mac_input(seq, ctype, version, fragment):
    """seq_num(8) || type(1) || version(2) || length(2) || fragment.

    `length` is the fragment length BEFORE the MAC is appended, and TLS 1.0
    includes the version field where SSL 3.0 does not."""
    return (seq.to_bytes(8, "big") + bytes([ctype]) +
            version.to_bytes(2, "big") + len(fragment).to_bytes(2, "big") + fragment)


def protect(mac_key, rc4, seq, ctype, fragment, hashmod, version=VERSION,
            mac_seq=None, mac_version=None):
    """Build one record. mac_seq / mac_version override only what the MAC is
    computed over, which is how the negative vectors are made."""
    m = hmac.new(mac_key,
                 mac_input(seq if mac_seq is None else mac_seq,
                           ctype,
                           version if mac_version is None else mac_version,
                           fragment),
                 hashmod).digest()
    ct = rc4.crypt(fragment + m)
    return (bytes([ctype]) + version.to_bytes(2, "big") +
            len(ct).to_bytes(2, "big") + ct)


def blob(tag, n):
    out = b""
    h = hashlib.sha256(tag).digest()
    while len(out) < n:
        h = hashlib.sha256(h).digest()
        out += h
    return out[:n]


SEQUENCE = [
    (CT_HANDSHAKE, b"\x14\x00\x00\x0c" + blob(b"finished", 12)),  # a Finished
    (CT_APPLICATION_DATA, b"GET /login.htm HTTP/1.0\r\n\r\n"),
    (CT_APPLICATION_DATA, b""),                                   # empty fragment
    (CT_APPLICATION_DATA, blob(b"bulk", 1000)),                   # spans many keystream bytes
    (CT_ALERT, b"\x01\x00"),                                      # close_notify
]


def emit_sequence(name, hashmod, mac_key, enc_key):
    rc4 = RC4(enc_key)
    print(f"[[maybe_unused]] static const RecVec {name}[] = {{")
    for seq, (ctype, frag) in enumerate(SEQUENCE):
        rec = protect(mac_key, rc4, seq, ctype, frag, hashmod)
        print(f'    {{ {ctype}, "{frag.hex()}",')
        print(f'      "{rec.hex()}" }},')
    print("};\n")


def main():
    mac_md5, enc_md5 = blob(b"mac-md5", 16), blob(b"enc-md5", 16)
    mac_sha, enc_sha = blob(b"mac-sha", 20), blob(b"enc-sha", 16)

    print("// Generated by tests/gen_record_vectors.py -- do not edit by hand.")
    print("// An independent Python model of TLS 1.0 record protection (RC4 suites).")
    print("// Each *_RECORDS array is a SEQUENCE produced by one RC4 object, so it")
    print("// only reproduces if the keystream is continuous across records.\n")

    print("struct RecVec { uint8_t type; const char* plaintext_hex; const char* record_hex; };")
    print("struct NegVec { const char* desc; const char* record_hex; };\n")

    print(f'[[maybe_unused]] static const char* MD5_MAC_KEY = "{mac_md5.hex()}";')
    print(f'[[maybe_unused]] static const char* MD5_ENC_KEY = "{enc_md5.hex()}";')
    print(f'[[maybe_unused]] static const char* SHA_MAC_KEY = "{mac_sha.hex()}";')
    print(f'[[maybe_unused]] static const char* SHA_ENC_KEY = "{enc_sha.hex()}";\n')

    emit_sequence("MD5_RECORDS", hashlib.md5, mac_md5, enc_md5)
    emit_sequence("SHA1_RECORDS", hashlib.sha1, mac_sha, enc_sha)

    # Negative cases. Each is the FIRST record after ChangeCipherSpec, so the
    # reader's keystream position and sequence number are both zero, and the
    # only thing wrong is the one field named in the description.
    frag = b"one variable at a time"
    negatives = []

    rc4 = RC4(enc_md5)
    negatives.append(("MAC computed over seq 5, sent as seq 0",
                      protect(mac_md5, rc4, 0, CT_APPLICATION_DATA, frag,
                              hashlib.md5, mac_seq=5)))
    rc4 = RC4(enc_md5)
    negatives.append(("MAC computed over version 0x0300 (SSL 3.0)",
                      protect(mac_md5, rc4, 0, CT_APPLICATION_DATA, frag,
                              hashlib.md5, mac_version=0x0300)))
    rc4 = RC4(enc_md5)
    rec = bytearray(protect(mac_md5, rc4, 0, CT_APPLICATION_DATA, frag, hashlib.md5))
    rec[5] ^= 0x01                                     # flip a ciphertext bit
    negatives.append(("a flipped ciphertext bit", bytes(rec)))

    rc4 = RC4(enc_md5)
    rec = bytearray(protect(mac_md5, rc4, 0, CT_APPLICATION_DATA, frag, hashlib.md5))
    rec[-1] ^= 0x80                                    # flip a MAC bit
    negatives.append(("a flipped MAC bit", bytes(rec)))

    # MAC covers CT_ALERT, but the header claims application_data. The MAC must
    # bind the content type, or a record can be relabelled in flight.
    rc4 = RC4(enc_md5)
    rec = protect(mac_md5, rc4, 0, CT_ALERT, frag, hashlib.md5)
    negatives.append(("MAC computed for a different content type",
                      bytes([CT_APPLICATION_DATA]) + rec[1:]))

    print("[[maybe_unused]] static const NegVec MD5_NEGATIVE[] = {")
    for desc, rec in negatives:
        print(f'    {{ "{desc}",')
        print(f'      "{rec.hex()}" }},')
    print("};\n")

    # key_block split, RFC 2246 6.3 ordering.
    kb = blob(b"key-block", 2 * 16 + 2 * 16)
    print(f'[[maybe_unused]] static const char* KEY_BLOCK_HEX = "{kb.hex()}";')
    print(f'[[maybe_unused]] static const char* KB_CLIENT_MAC = "{kb[0:16].hex()}";')
    print(f'[[maybe_unused]] static const char* KB_SERVER_MAC = "{kb[16:32].hex()}";')
    print(f'[[maybe_unused]] static const char* KB_CLIENT_KEY = "{kb[32:48].hex()}";')
    print(f'[[maybe_unused]] static const char* KB_SERVER_KEY = "{kb[48:64].hex()}";')


if __name__ == "__main__":
    main()
