#!/usr/bin/env python3
"""Regenerate tests/bigint_vectors.inc.

Reference values come from Python's arbitrary-precision pow(m, e, n), which is
the same validate-against-a-known-good-implementation approach the rest of this
repo uses for the ported Java classes.

The 1024-bit modulus below is the public key of the iLO 2 at 192.0.2.10
(self-signed, CN=ILOUSE951N96F, e=65537, expired 2022-12-05). It is public key
material -- the device hands it to anyone who opens a TLS connection -- so it is
safe to commit, and using the real modulus means the bignum is exercised against
the exact operand the handshake will use.

    python tests/gen_bigint_vectors.py > tests/bigint_vectors.inc
"""
import hashlib

ILO_MODULUS_HEX = (
    "BDE79C0E220D27830FFA815173D9BF7DEA6E29C459C1F04D9359A2467C51290278207B6776FDDF03"
    "ECE6F44A37B61C36AB6646EC497E48FAEA2E1567F91FE8834B1AA6760EB1714475AFD1459D8D5AB1"
    "32BE495B55B80C82FDA5000997A1F31BBD57C4861A060E5FB9B28EE0D64E4FEAA7DCBB5FD8ECCA49"
    "278B9AE5005FD04B"
)


def emit(name, items):
    print(f"[[maybe_unused]] static const Vec {name}[] = {{")
    for m_hex, e, mod_hex, r_hex in items:
        print(f'    {{ "{m_hex}", {e}u, "{mod_hex}", "{r_hex}" }},')
    print("};\n")


def msgs(count, nbytes):
    """Deterministic pseudo-random messages, so this file is reproducible."""
    h = hashlib.sha256(b"ilo2-bigint-vectors").digest()
    out = []
    while len(out) < count:
        buf = b""
        while len(buf) < nbytes:
            h = hashlib.sha256(h).digest()
            buf += h
        out.append(int.from_bytes(buf[:nbytes], "big"))
    return out


def main():
    n = int(ILO_MODULUS_HEX, 16)

    print("// Generated by tests/gen_bigint_vectors.py -- do not edit by hand.")
    print("// Reference values come from Python's arbitrary-precision pow(m, e, n).")
    print("// The 1024-bit modulus is the REAL certificate from the iLO 2 at")
    print("// 192.0.2.10 (self-signed, CN=ILOUSE951N96F, e=65537).\n")
    print(f'[[maybe_unused]] static const char* ILO_MODULUS_HEX =\n    "{ILO_MODULUS_HEX}";\n')

    # Small / edge cases. 3233 is the textbook RSA modulus (p=61, q=53), whose
    # phi is 3120 -- so e=17 and d=2753 are inverses and both fit in a uint32,
    # which lets the C++ test round-trip encrypt/decrypt without ever needing a
    # big-exponent modexp.
    items = []
    small_n = 3233
    for m in (0, 1, 2, 42, 3232, 65535):
        for e in (3, 17, 65537):
            items.append((f"{m:x}", e, f"{small_n:x}", f"{pow(m, e, small_n):x}"))
    emit("SMALL_VECTORS", items)

    # Full-width 1024-bit operations against the real iLO modulus.
    items = []
    for m in msgs(6, 128):
        m %= n
        for e in (3, 65537):
            items.append((f"{m:x}", e, ILO_MODULUS_HEX.lower(), f"{pow(m, e, n):x}"))
    # Boundaries. m == n and m == 2n matter more than they look: they are the
    # only inputs where the running remainder inside binary reduction hits the
    # modulus EXACTLY, which is what distinguishes a correct ">= n, subtract"
    # from an off-by-one "> n, subtract". Random operands never reach that state,
    # so without these two a broken conditional passes every other vector.
    for m in (0, 1, n - 1, n, n + 1, 2 * n, n + 12345):
        items.append((f"{m:x}", 65537, ILO_MODULUS_HEX.lower(), f"{pow(m, 65537, n):x}"))
    emit("ILO_VECTORS", items)


if __name__ == "__main__":
    main()
