#!/usr/bin/env python3
"""Regenerate tests/cert_fixture.inc from a DER-encoded certificate.

The default fixture is the certificate the iLO 2 at 10.10.123.130 serves on
port 443. It is public material -- the device hands it to anyone who opens a
TLS connection -- and having the real thing in the test suite means the DER
walk is exercised against the exact bytes the handshake will see, including
this certificate's specific quirks:

  * a 1024-bit modulus whose top bit is set, so DER encodes it as 129 bytes
    with a leading 0x00 sign pad -- the key size is 128, and conflating the two
    is the classic way to get RSA wrong,
  * no [0] EXPLICIT version field (it is a v1 certificate from 2002), so any
    parser that reaches SubjectPublicKeyInfo by counting TBS children from a
    fixed offset will land in the wrong place.

    python tests/gen_cert_fixture.py path/to/cert.der > tests/cert_fixture.inc
"""
import sys



# --- an independent DER walk -------------------------------------------------
# Deliberately a second implementation rather than a call into the C++ one: the
# expected modulus and exponent below are what a DIFFERENT parser extracts from
# the same bytes, so tls/der.hpp is checked against something, not against
# itself.

RSA_OID = bytes([0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x01])


def tlv(buf, off):
    """Return (tag, content, next_offset) for the TLV at buf[off]."""
    tag = buf[off]
    off += 1
    n = buf[off]
    off += 1
    if n & 0x80:
        k = n & 0x7F
        n = int.from_bytes(buf[off:off + k], "big")
        off += k
    if off + n > len(buf):
        raise ValueError("truncated")
    return tag, buf[off:off + n], off + n


def find_rsa_key(der):
    _, cert, _ = tlv(der, 0)
    _, tbs, _ = tlv(cert, 0)
    off = 0
    while off < len(tbs):
        tag, content, off = tlv(tbs, off)
        if tag != 0x30:
            continue
        try:
            t, alg, after_alg = tlv(content, 0)
            if t != 0x30:
                continue
            t, oid, _ = tlv(alg, 0)
            if t != 0x06 or oid != RSA_OID:
                continue
            t, bits, _ = tlv(content, after_alg)
            if t != 0x03 or bits[0] != 0x00:
                continue
            t, rsa, _ = tlv(bits, 1)
            if t != 0x30:
                continue
            t, n, after_n = tlv(rsa, 0)
            t2, e, _ = tlv(rsa, after_n)
            return n.lstrip(b"\x00"), e.lstrip(b"\x00")
        except (IndexError, ValueError):
            continue
    raise SystemExit("no RSA SubjectPublicKeyInfo found")


def wrap(hexstr, per_line=32):
    for i in range(0, len(hexstr), per_line * 2):
        yield hexstr[i:i + per_line * 2]


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_cert_fixture.py <cert.der>")
    der = open(sys.argv[1], "rb").read()

    print("// Generated by tests/gen_cert_fixture.py -- do not edit by hand.")
    print("// The live certificate from the iLO 2 at 10.10.123.130:")
    print("//   self-signed, CN=ILOUSE951N96F, 1024-bit RSA, e=65537,")
    print("//   md5WithRSAEncryption, valid 2002-12-05 .. 2022-12-05 (EXPIRED).")
    print("// Public key material; it is served to any client that connects.\n")
    print(f"// {len(der)} bytes")
    print("[[maybe_unused]] static const char* ILO_CERT_DER_HEX =")
    lines = list(wrap(der.hex()))
    for i, line in enumerate(lines):
        tail = ";" if i == len(lines) - 1 else ""
        print(f'    "{line}"{tail}')
    print()

    n, e = find_rsa_key(der)
    print("// Extracted by this script's own independent DER walk:")
    print(f'[[maybe_unused]] static const char* ILO_CERT_MODULUS_HEX =')
    mod_lines = list(wrap(n.hex()))
    for i, line in enumerate(mod_lines):
        tail = ";" if i == len(mod_lines) - 1 else ""
        print(f'    "{line}"{tail}')
    print(f"[[maybe_unused]] static const uint32_t ILO_CERT_EXPONENT = "
          f"{int.from_bytes(e, 'big')}u;")
    print(f"[[maybe_unused]] static const size_t ILO_CERT_MODULUS_BYTES = {len(n)};")


if __name__ == "__main__":
    main()
